#!/usr/bin/env bash
set -euo pipefail

EBIN=$(rebar3 path --ebin --app concuerror)
cd cover
export COVER_COMBINE=all.coverdata
./cover-report data || true
covertool/covertool -cover $COVER_COMBINE -ebin $EBIN -appname concuerror
