#!/bin/bash

TESTS="simple_spawn spawn_and_send receiver spawn crasher crasher2 \
blocking_trace receiver_trace \
two_receiver_trace two_receiver_trace_2 two_receiver_trace_3 \
spawner_trace spawner_trace_2 spawner_trace_3 spawner_trace_4 spawner_trace_5 \
many_spawn three_send \
afterer after_crasher \
opt_afterer opt_after_crasher \
not_really_blocker not_really_blocker_crasher \
independent_receivers"

compare() {
    echo -n "$1 "
    ./concuerror -f test.erl -p inf -t test $1 > /dev/null
    grep -v blocks results.txt > normal
    ./concuerror -f test.erl -t test $1 --dpor > /dev/null
    mv results.txt dpor
    if diff -q normal dpor; then
        echo "OK"
    else
        echo "ERROR!"
        diff normal dpor
        exit 1
    fi
}

make -s
if [ -n "$1" ]; then
    compare $1
    exit 0
else
    for t in $TESTS; do
        compare $t
    done
    exit 0
fi