#!/bin/bash

TESTS="simple_spawn spawn_and_send receiver spawn crasher crasher2 \
blocking_trace receiver_trace \
two_receiver_trace two_receiver_trace_2 two_receiver_trace_3 \
spawner_trace spawner_trace_2 spawner_trace_3 spawner_trace_4 spawner_trace_5 \
many_spawn three_send \
afterer after_crasher \
opt_afterer opt_after_crasher \
not_really_blocker not_really_blocker_crasher \
independent_receivers"

compare() {
    echo -n "$1 "
    Module=$(basename $2 .erl)
    Command="./concuerror -f $2 -t $Module $1"
    $Command -p inf > /dev/null
    mv results.txt normal
    $Command --dpor_fake > /dev/null
    mv results.txt dpor
    if diff -q normal dpor; then
        echo "OK"
    else
        echo "ERROR!"
        diff normal dpor
        exit 1
    fi
}

make -s
if [ "$1" = "-d" ]; then
    for t in $(find $2 -maxdepth 1 -type f); do
        compare $(basename $t .erl) $t
    done
    exit 0
elif [ -n "$1" ]; then
    compare $1 test.erl
    exit 0
else
    for t in $TESTS; do
        compare $t test.erl
    done
    exit 0
fi