#!/bin/bash

CONCUERROR=${CONCUERROR:-$(which concuerror)}
DIFFER=${DIFFER:-$(pwd)/../../../tests/differ}
ORIG=$(pwd)

export DIFFPRINTER=${DIFFPRINTER:-$(pwd)/thediff}

. ../print_colors

function abort {
    cd $ORIG
    . $DIFFPRINTER
    print_red "FAILED"
}

function testing {
    echo -n "$1..."
}

function good {
    print_green "ok"
}

set -e
trap 'abort' 0

cd gproc
for i in t_simple_reg t_simple_reg_or_locate t_reg_or_locate2 test1 test2 test3 test4; do
    testing "Test $i"
    RES=$i.out
    REF=$(readlink -m ../ref/$RES)
    RUN=$(readlink -m ../run/$RES)
    $CONCUERROR -i 100 --assume_racing=false -q -k --pa ebin -f ../test.erl -m test -t $i -o $RUN || true
    (bash $DIFFER $REF $RUN && rm $RUN && good) || false
done

trap - 0

print_green "SUCCESS!"
