#!/usr/bin/env bash

set -o pipefail

DIFFPRINTER=${DIFFPRINTER-thediff}

DIFF=$(mktemp)

diff \
    <(grep "  Summary" $1 2> /dev/null || echo empty1) \
    <(grep "  Summary" $2 2> /dev/null || echo empty2) \
    > $DIFF

if [ "$?" -ne 0 ]; then
    echo echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" >> $DIFFPRINTER
    echo echo "New result:" >> $DIFFPRINTER
    echo "cat $2" >> $DIFFPRINTER
    echo echo "Diff from $1:" >> $DIFFPRINTER
    echo "cat $DIFF" >> $DIFFPRINTER
    exit 1
fi
