#!/usr/bin/env bash

set -o pipefail
diff \
    <(grep -B1 "  Summary" $1 2> /dev/null || echo empty1) \
    <(grep -B1 "  Summary" $2 2> /dev/null || echo empty2) \
    > /dev/null

if [ "$?" -ne 0 ]; then
    echo echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" >> thediff
    echo echo $2 >> thediff
    echo cat $2 >> thediff
    exit 1
fi
