#!/bin/bash
set -e

cd gproc
for i in t_simple_reg t_simple_reg_or_locate t_reg_or_locate2; do
    echo -n "Test $i "
    RES=$i.out
    REF=../ref/$RES
    RUN=../run/$RES
    $CONCUERROR --pa ebin -q --timeout -1 -f ../test.erl -m test -t $i -o $RUN || true
    bash $DIFFER $REF $RUN
    echo ok
done