#!/bin/bash

. header

print_blue "$0"

testing "Basic message is produced for error detection"
! concuerror_console -f src/buggy.erl
consolehas "Errors were found! (check concuerror_report.txt)"

testing "Deadlock shows messages"
! concuerror_console -f src/deadlock.erl
outputhas "Mailbox contents: \[foo\]"

testing "Symbolic registered names Info"
! concuerror_console -f src/register.erl
consolehas "Showing PIDs as \"<symbolic name(/last registered name)>\" ('-h symbolic_names')."

testing "Symbolic registered names error info"
! concuerror_console -f src/register.erl
outputhas "process <P.1/foo> exited abnormally"

testing "Decent stacktrace reports"
! concuerror_console -f src/stacktrace.erl
outputhas "[{file,\"src/stacktrace.erl\"},{line,93}]"

. footer
