#!/bin/bash

. header

print_blue "$0"

testing "Progress bar sample"
$CONCUERROR -f src/many_scheds.erl -v1 2>&1 | tr '\033' '#' | cat > $Out
print_ok
Target="    Errors |  Explored | Planned |  ~ Rate |  Total(?) | Time(?)"
testing "... and output has \"$Target\""
if ! grep -q "$Target" $Out; then
    exit 1
fi
print_ok
Target="         0 |         0 |       0 |   <1 /s |   unknown | unknown"
testing "... and output has \"$Target\""
if ! grep -q "$Target" $Out; then
    exit 1
fi
good

testing "Progress bar sample for source"
$CONCUERROR -f src/many_scheds.erl -v1 --dpor source 2>&1 | tr '\033' '#' | cat > $Out
print_ok
Target="    Errors |  Explored | Planned |  ~ Rate |  Total(?) | Time(?)"
testing "... and output has \"$Target\""
if ! grep -q "$Target" $Out; then
    exit 1
fi
print_ok
Target="         0 |         0 |       0 |   <1 /s |   unknown | unknown"
testing "... and output has \"$Target\""
if ! grep -q "$Target" $Out; then
    exit 1
fi
good

testing "Progress bar sample with hard bound"
$CONCUERROR -f src/many_scheds.erl -v1 --dpor source -i 300 2>&1 | tr '\033' '#' | cat > $Out
print_ok
Target="    Errors |  Explored | Planned |  ~ Rate |  Total(?) | Time(?)"
testing "... and output has \"$Target\""
if ! grep -q "$Target" $Out; then
    exit 1
fi
print_ok
Target="         0 |         0 |       0 |   <1 /s |   unknown | unknown"
testing "... and output has \"$Target\""
if ! grep -q "$Target" $Out; then
    exit 1
fi
good

testing "Progress bar sample with delay bound"
$CONCUERROR -f src/many_scheds.erl -v1 -b 7 2>&1 | tr '\033' '#' | cat > $Out
print_ok
Target="    Errors |  Explored | Planned |  ~ Rate |  Total(?) | Time(?)"
testing "... and output has \"$Target\""
if ! grep -q "$Target" $Out; then
    exit 1
fi
print_ok
Target="         0 |         0 |       0 |   <1 /s |   unknown | unknown"
testing "... and output has \"$Target\""
if ! grep -q "$Target" $Out; then
    exit 1
fi
good

testing "No tip for harmless exit signals"
! concuerror_console -f src/harmless_exit.erl -k
print_ok
Target="An abnormal exit signal"
testing "... and output does not have \"$Target\""
if grep -q "$Target" $Out; then
    exit 1
fi
good

testing "Graph format"
concuerror_console -f src/race_info.erl --show_races --graph graph.dot
print_ok
testing "... and graph is the same as the ref/graph.dot"
diff graph.dot ref/graph.dot
rm graph.dot
good

testing "Correct race info"
concuerror_console -f src/race_info.erl --show_races
print_ok
Target="Interleaving #2"
testing "... and output does not have \"$Target\""
if grep -q "$Target" $Out; then
    exit 1
fi
outputhas "New races found"

testing "Basic message is produced for error detection"
! concuerror_console -f src/buggy.erl
consolehas "Errors were found! (check concuerror_report.txt)"

testing "Deadlock shows messages"
! concuerror_console -f src/deadlock.erl
outputhas "Mailbox contents: \[foo\]"

testing "Symbolic registered names Info"
! concuerror_console -f src/register.erl
consolehas "Showing PIDs as \"<symbolic name(/last registered name)>\" ('-h symbolic_names')."

testing "Symbolic registered names error info"
! concuerror_console -f src/register.erl
outputhas "process <P.1/foo> exited abnormally"

testing "Decent stacktrace reports"
! concuerror_console -f src/stacktrace.erl
outputhas "[{file,\"src/stacktrace.erl\"},{line,93}]"

. footer
