#!/usr/bin/env bash

set -e

export COVER_COMBINE=all.coverdata

THISDIR=$(dirname $0)
REPO_LATEST=`$THISDIR/get_latest_travis $THISDIR/../.travis.yml`

if [ "$REPO_LATEST" = "$TRAVIS_OTP_RELEASE" ]; then
  echo "Generate coverage report..."
  cd cover
  ./cover-report data
  covertool/covertool -cover $COVER_COMBINE -src ../src -output cover.xml
  echo "Report generated!"
  codecov
  echo "Report sent!"
fi
