#!/usr/bin/env bash

. $(dirname $0)/header

if [ "$COLLECT_COVERAGE" = "true" ]; then
  echo "Prepare to collect coverage data."
  make cover/data
  cd cover
  git clone https://github.com/concuerror/covertool.git --branch 0.0.0-concuerror1
  cd covertool
  make compile
  echo "Ready to collect coverage data!"
fi
