#!/usr/bin/env bash

# Recover plt
cp plts/plt-$TRAVIS_OTP_RELEASE .concuerror_plt || true

set -e

THISDIR=$(dirname $0)
REPO_LATEST=`$THISDIR/get_latest_travis $THISDIR/../.travis.yml`

if [ "$REPO_LATEST" = "$TRAVIS_OTP_RELEASE" ]; then
  echo "Testing latest release. Prepare to collect coverage data."
  make cover/data
  cd cover
  git clone https://github.com/idubrov/covertool.git
  cd covertool
  make compile
  echo "Ready to collect coverage data!"
fi
