#!/usr/bin/env bash

set -xe

THISDIR=$(dirname $0)
REPO_LATEST=`$THISDIR/get_latest_travis $THISDIR/../.travis.yml`

if [ "$REPO_LATEST" = "$TRAVIS_OTP_RELEASE" ]; then
    if [ -z ${FLAG+x} ]; then
        echo "FLAG not set, so no coverage generated"
    else
        COLLECT_COVERAGE=true
    fi
fi
