#!/usr/bin/env bash

set -e

THISDIR=$(dirname $0)
REPO_LATEST=`$THISDIR/get_latest_travis $THISDIR/../.travis.yml`

cd $THISDIR/..

if [ "$REPO_LATEST" = "$TRAVIS_OTP_RELEASE" ]; then
  echo "Testing latest release. Prepare to collect coverage data."
  make cover/data
  cd cover
  ./get-coveralls
  export CONCUERROR_COVER=$(pwd)/data
  cd ..
  echo "Ready to collect coverage data!"
fi

echo "Running make $1"
make $1
echo "make $1 done"

if [ "$REPO_LATEST" = "$TRAVIS_OTP_RELEASE" ]; then
  echo "Generate and send coverage report..."
  cd cover
  ./cover-report data > /dev/null
  echo "Report sent!"
fi
