#!/usr/bin/env bash

set -e

THISDIR=$(dirname $0)
REPO_LATEST=`$THISDIR/get_latest_travis $THISDIR/../.travis.yml`

if [ "$REPO_LATEST" = "$TRAVIS_OTP_RELEASE" ]; then
  export CONCUERROR_COVER=$(pwd)/cover/data
fi

make $1
