#!/usr/bin/env bash

. $(dirname $0)/header

if [ "$COLLECT_COVERAGE" = "true" ]; then
  ## Use non escriptized version for coverage report
  export CONCUERROR=$(pwd)/priv/concuerror
  export CONCUERROR_COVER=$(pwd)/cover/data
fi

make $1
