#!/usr/bin/env bash

DIR=$(dirname $(readlink -f $0))
. $DIR/travis_enable_cover_if_latest

curl -sO https://raw.githubusercontent.com/kerl/kerl/master/kerl
chmod a+x kerl
LATEST=`./kerl update releases | tr ' ' '\n' | tail -n1`
rm ./kerl

set +x

if [ "$LATEST" != "$TRAVIS_OTP_RELEASE" ]; then
    cat <<EOF

Error: OTP release $LATEST is available via kerl but this test has been
configured in .travis.yml to use $TRAVIS_OTP_RELEASE (as the most recent release).

Fix: Update .travis.yml to use $LATEST *FOR THIS TEST ONLY*.

Warning: This test WILL KEEP FAILING, either with 'X' (but a DIFFERENT message
will be shown) or with '!':

- If the test fails with 'X', read the new message for further instructions.
- If the test fails with '!', Travis maintainers have not yet enabled the newer
  OTP release on Travis. Wait until this test fails with 'X' again.

This approach is not the smoothest, but it is a simple way to perform the test:
  "Does Travis support the latest OTP release"

EOF
    false
fi

if [ "$LATEST" != "$REPO_LATEST" ]; then
    cat <<EOF

Error: OTP release $LATEST is available on Travis but .travis.yml specifies
$REPO_LATEST as the latest release used for all tests.

Fix: Update .travis.yml to use $LATEST as the top otp_release (and make sure
to follow the rest of the specifications written there).

EOF
    false
fi
