#!/usr/bin/env bash

set -xe

DIR=$(dirname $(readlink -f $0))
TOP=$(readlink -f $DIR/..)

REPO_LATEST=`$DIR/get_latest_travis $TOP/.travis.yml`

if [ "$REPO_LATEST" = "$TRAVIS_OTP_RELEASE" ]; then
    if [ -z ${FLAG+x} ]; then
        echo "FLAG not set, so no coverage generated"
    else
        ENABLE_COVER=true
    fi
fi
