#!/bin/bash

compare() {
    echo -n "$1 "
    O="results/$T"
    NO="new_results/$T"
    ../concuerror -f src/$T.erl -t $T $T \
        -o $NO --dpor -p inf > /dev/null
    if diff -q $O $NO; then
        echo "OK"
    else
        echo "ERROR!"
        mv $NO $O
    fi
}

cd ..
make -s
cd dpor_tests
mkdir -p new_results
if [ -n "$1" ]; then
    Name=$(basename $1 .erl)
    compare $Name
    exit 0
else
    for i in $(ls src); do 
        T=$(basename $i .erl);
        compare $T
    done
fi
