#!/bin/bash

compare() {
    echo -n "$1 "
    O="results/$1"
    NO="new_results/$1"
    ../concuerror -f src/$1.erl -t $1 $1 \
        -o $NO --dpor -p inf > log
    if diff -q $O $NO; then
        echo "OK"
        rm $NO
    else
        echo "ERROR!"
        diff $O $NO
        exit 1
    fi
}

cd $(dirname $0)
cd ..
make -s
cd dpor_tests
mkdir -p new_results
if [ -n "$1" ]; then
    compare $(basename "$1" .erl)
    exit 0
else
    for i in $(ls src); do 
        compare $(basename "$i" .erl)
    done
    exit 0
fi
