#!/bin/bash

Out=concuerror_report.txt
CONCUERROR=${CONCUERROR:-concuerror}
CONCUERROR="$CONCUERROR --timeout -1"

function abort {
    echo -e "\e[1;31m FAILED\e[0m"
    echo cat $Out
    cat $Out
    echo -e "\e[1;31m FAILED\e[0m"
}

function testing {
    echo -n "$1..."
}

function good {
    echo -e " \e[1;32mok\e[0m"
}

function mygrep {
    grep -q "$1" $Out
}

function has {
    testing "Output has $1"
    mygrep "$1"
    good
}

set -e
trap 'abort' 0

echo -e "\e[0;34mPart 1\e[0m"

testing "Concuerror has help option"
$CONCUERROR -h 2> /dev/null
good

cd poolboy

testing "Running Concuerror"
! $CONCUERROR -q -f poolboy_tests_1.erl -m poolboy_tests_1 -t pool_startup
good

testing "Output filename is correct"
[ -e $Out ]
good

has Info
has Warning
has Tip

testing "Abnormal exit found"
mygrep "\* At step .* process P\.1 exited abnormally"
good

testing "Rerun"
! $CONCUERROR -q -f poolboy_tests_1.erl -m poolboy_tests_1 -t pool_startup --pa .eunit
good

testing "Tips and errors are there"
mygrep "A process crashed with reason"
mygrep "An abnormal exit signal was sent to a process."
mygrep "A process crashed with reason 'shutdown'."
mygrep "Stop testing on first error."
good

testing "Correct error"
mygrep "\* At step .* process P exited abnormally"
good

echo -e "\e[0;34mPart 2\e[0m"

testing "Turn off symbolic"
! $CONCUERROR -q -f poolboy_tests_1.erl -m poolboy_tests_1 -t pool_startup  \
    --pa .eunit --symbolic_names false
mygrep "\* At step .* process <0."
good

testing "Use an after timeout"
! $CONCUERROR -q -f poolboy_tests_1.erl -m poolboy_tests_1 -t pool_startup \
     --pa .eunit --after_timeout 1000
mygrep "{after_timeout,1000}"
good

testing "Treat shutdown as normal"
$CONCUERROR -q -f poolboy_tests_1.erl -m poolboy_tests_1 -t pool_startup \
    --pa .eunit --after_timeout 1000 --treat_as_normal shutdown
mygrep "Some abnormal exit reasons were treated as normal ('--treat_as_normal')."
good

testing "Find a deadlock"
! $CONCUERROR -q -f poolboy_tests_1.erl -m poolboy_tests_1 --pa .eunit \
 -t pool_startup_no_stop
mygrep "* Blocked at a 'receive' (\"deadlocked\"; other processes have exited):"
good

testing "Ignore a deadlock"
$CONCUERROR -q -f poolboy_tests_1.erl -m poolboy_tests_1 --pa .eunit \
    -t pool_startup_no_stop --ignore_error deadlock
mygrep "Summary: 0 errors, 1/1 interleavings explored"
good

trap - 0

echo -e "\e[1;32mSUCCESS!\e[0m"
