#!/usr/bin/env bash

THISDIR=$(dirname $0)

curl -sO https://raw.githubusercontent.com/yrashk/kerl/master/kerl
chmod a+x kerl
LATEST=`./kerl update releases | tr ' ' '\n' | tail -n1`
rm ./kerl
REPO=`$THISDIR/get_latest_travis $THISDIR/../.travis.yml`
if [ $LATEST != $REPO ]; then
    printf "\nA newer OTP release is available!\n"
    printf " (.travis.yml has $REPO on top, kerl also has $LATEST)\n\n"
    false
fi
