#!/bin/bash

. header

testing "Concuerror has help option"
$CONCUERROR 2> $Console
consolehas Usage

testing "Report unknown arguments"
! $CONCUERROR unknown_argument 2> $Console
consolehas "Unknown argument"

testing "Report missing arguments"
! $CONCUERROR -t 2> $Console
consolehas "No argument given for"

testing "Show all options has > 50 lines"
if [ $($CONCUERROR -h all 2>&1 | wc -l) -lt 50 ]; then
    abort
fi
good

testing "Get help for long"
$CONCUERROR -h help 2> $Console
consolehas "Without an argument, prints info for basic options."

testing "Get help for short"
$CONCUERROR -h h 2> $Console
consolehas "Without an argument, prints info for basic options."

testing "Get help for prefixed"
$CONCUERROR -h --help 2> $Console
consolehas "Without an argument, prints info for basic options."

testing "Unknown argument to help"
! $CONCUERROR -h elp 2> $Console
consolehas "Invalid option name/keyword (as argument to --help)"

testing "No additional help available"
$CONCUERROR -h version 2> $Console
consolehas "No additional help available."

testing "Help for keyword"
$CONCUERROR -h bound 2> $Console
consolehas "Only showing options with the keyword 'bound'."

testing "Help for keyword with dashes"
$CONCUERROR -h keep-going 2> $Console

testing "Version"
$CONCUERROR --version 2> $Console
consolehas "Concuerror v"

testing "Bad entry point"
! $CONCUERROR -f foo.erl -t ban 2> $Console
consolehas "The entry point foo:ban/0 is invalid."

testing "Default verbosity has info"
$CONCUERROR -f foo.erl 2> $Console
consolehas "Info:"

testing "Verbosity and quiet"
! $CONCUERROR -v --quiet 2> $Console
consolehas "'--verbosity' specified together with '--quiet'."

testing "Too much verbosity"
! $CONCUERROR -vvvvvvvvv 2> $Console
consolehas "make dev"

testing "We found erlang without help"
$CONCUERROR -m erlang -t module_info 2> $Console
good

. footer
