#!/bin/bash

. header

print_blue "$0"

testing "Symbolic registered names Info"
! concuerror_console -f src/register.erl
consolehas "Showing PIDs as \"<symbolic name(/last registered name)>\" ('-h symbolic_names')."

testing "Symbolic registered names error info"
! concuerror_console -f src/register.erl
outputhas "process <P.1/foo> exited abnormally"

testing "No warnings for multiple -pa"
concuerror_console -vvvv -f src/foo.erl -pa .. src
print_ok
testing "... and console does not have \"Warning\""
if grep -q "Warning" $Console; then
    exit 1
fi
good

testing "Excluding works minimally"
concuerror_console -f src/excluding.erl -f src/excluded.erl -x excluded -m excluding
consolehas "1/1"

testing "Mixed case options are ok"
concuerror_console --VeRsIoN
consolehas "Concuerror v"

testing "Tip for attributes"
concuerror_console -a 1000 --assume_racing -d 5000 --ignore_error abnormal_exit deadlock -i 6000 -k -f src/foo.erl
consolehas "help attributes"

testing "Help for attributes"
concuerror_console -h attributes
consolehas "the following attributes in the module"

testing "Disable output"
rm -rf $Out
concuerror_console -f src/foo.erl --no_output
consolehas "No output report will be generated"
testing "... and output file doesn't exist."
if [ ! -f "$Out" ]; then
    good
else
    exit 1
fi

testing "Total silence"
rm -rf $Out
concuerror_console -f src/foo.erl --no_output -q
good
testing "... and output file doesn't exist"
if [ ! -f "$Out" ]; then
    print_ok
else
    exit 1
fi
testing "... and console is empty"
if [ ! -f "$Console" ]; then
    good
else
    exit 1
fi

testing "Nonexistent input file"
! concuerror_console -f nonexistent
consolehas "Error: nonexistent is not a .erl or .beam file"

testing "Bad .erl input file"
! concuerror_console -f src/bad.erl > /dev/null
consolehas "Error: could not compile src/bad.erl (try to add the .beam file instead)"

testing "BEAM input file"
rm -f foo.beam
erlc src/foo.erl
concuerror_console -f foo.beam
good
rm foo.beam

testing "Bad BEAM input file"
rm -f foo.beam
cp src/foo.erl foo.beam
! concuerror_console -f foo.beam
consolehas "Error:"
rm foo.beam

testing "Warn about shadowing"
rm -f foo.beam
erlc src/foo.erl
concuerror_console -f src/foo.erl
consolehas "Warning: File src/foo.erl shadows ./foo.beam (found in path)"
rm foo.beam

testing "Basic message is produced for error detection"
! concuerror_console -f src/buggy.erl
consolehas "Errors were found! (check concuerror_report.txt)"

testing "Input file without option"
concuerror_console src/foo.erl
consolehas "Converting dangling argument to '--file"

testing "No warnings for -vvvvvvv"
concuerror_console -vvvv -f src/foo.erl
print_ok
testing "... and console does not have \"Parsing\""
if grep -q "Parsing" $Console; then
    exit 1
fi
good

testing "Notify about synonym"
concuerror_console --ignore_error crash -f src/foo.erl
consolehas "\"--ignore_error crash\" converted to \"--ignore_error abnormal_exit\""

. footer
