#!/bin/bash

. header

echo -e "\e[0;34m$0\e[0m"

testing "Excluding works minimally"
concuerror_console -f exclude_modules/test.erl -f exclude_modules/excluded.erl -x excluded -m test
consolehas "1/1"

testing "Mixed case options are ok"
concuerror_console --VeRsIoN
consolehas "Concuerror v"

. footer
