#!/bin/bash

. header

print_blue "$0"

testing "Concuerror has help option"
concuerror_console
consolehas Usage

testing "Concuerror help returns basic help"
concuerror_console --help
consolehas 'basic'

testing "Report unknown arguments"
concuerror_console_fail unknown arguments
consolehas "Unknown argument"

testing "Report missing arguments"
concuerror_console_fail -t
consolehas "No argument given for"

testing "Show all options has > 50 lines"
concuerror_console -h all
if [ $(cat $Console | wc -l) -lt 50 ]; then
    abort
fi
good

testing "Get help for long"
concuerror_console -h help
consolehas "Without an argument, prints info for basic options."

testing "Get help for short"
concuerror_console -h h
consolehas "Without an argument, prints info for basic options."

testing "Get help for prefixed"
concuerror_console -h --help
consolehas "Without an argument, prints info for basic options."

testing "Unknown option"
concuerror_console_fail --unknown_option
consolehas "invalid option: --unknown_option"

testing "Unknown argument to help"
concuerror_console_fail -h elp
consolehas "invalid option/keyword (as argument to --help)"

testing "No additional help available"
concuerror_console -h version
consolehas "No additional help available."

testing "Help for keyword"
concuerror_console -h bound
consolehas "Only showing options with the keyword 'bound'."

testing "Help for keyword with dashes"
concuerror_console -h keep-going
consolehas "keep_going"

testing "Version"
concuerror_console --version
consolehas "Concuerror v"

testing "Bad entry point"
concuerror_console_fail -f src/foo.erl -t ban
consolehas "The entry point foo:ban/0 is invalid."

testing "Default verbosity has info"
concuerror_console -f src/foo.erl
consolehas "Info:"

testing "Verbosity and quiet"
concuerror_console_fail -v --quiet
consolehas "'--verbosity' specified together with '--quiet'."

testing "Too much verbosity"
concuerror_console_fail -vvvvvvvvv
consolehas "make dev"

testing "We found erlang without help"
concuerror_console -m erlang -t module_info
good

. footer
