#!/bin/bash

. header

print_blue "$0"

testing "Concuerror has help option"
concuerror_console
consolehas Usage

testing "Report unknown arguments"
! concuerror_console unknown_argument
consolehas "Unknown argument"

testing "Report missing arguments"
! concuerror_console -t
consolehas "No argument given for"

testing "Show all options has > 50 lines"
if [ $($CONCUERROR -h all 2>&1 | wc -l) -lt 50 ]; then
    abort
fi
good

testing "Get help for long"
concuerror_console -h help
consolehas "Without an argument, prints info for basic options."

testing "Get help for short"
concuerror_console -h h
consolehas "Without an argument, prints info for basic options."

testing "Get help for prefixed"
concuerror_console -h --help
consolehas "Without an argument, prints info for basic options."

testing "Unknown argument to help"
! concuerror_console -h elp
consolehas "Invalid option name/keyword (as argument to --help)"

testing "No additional help available"
concuerror_console -h version
consolehas "No additional help available."

testing "Help for keyword"
concuerror_console -h bound
consolehas "Only showing options with the keyword 'bound'."

testing "Help for keyword with dashes"
concuerror_console -h keep-going
consolehas "keep_going"

testing "Version"
concuerror_console --version
consolehas "Concuerror v"

testing "Bad entry point"
! concuerror_console -f foo.erl -t ban
consolehas "The entry point foo:ban/0 is invalid."

testing "Default verbosity has info"
concuerror_console -f foo.erl
consolehas "Info:"

testing "Verbosity and quiet"
! concuerror_console -v --quiet
consolehas "'--verbosity' specified together with '--quiet'."

testing "Too much verbosity"
! concuerror_console -vvvvvvvvv
consolehas "make dev"

testing "We found erlang without help"
concuerror_console -m erlang -t module_info
good

. footer
