#!/bin/bash

. header

print_blue "$0"

testing "Can find default in path"
rm -rf path
rm -rf foo.beam
mkdir path
erlc -o path foo.erl
concuerror_console --pz path -m foo
rm -rf path
good

testing "Script is symlinkable"
rm -rf concuerror
ln -s $(which $CONCUERROR) concuerror
./concuerror 2> $Console
rm -rf concuerror
good

testing "Limited automatic compilation with -m"
concuerror_console -m foo
good

testing "Long short option fixes works"
rm -rf path
rm -rf foo.beam
mkdir path
erlc -o path foo.erl
concuerror_console -pz path --ignore-error deadlock --m foo
consolehas "converted to"
rm -rf path

testing "Interleaving bound caps total"
concuerror_console -f six.erl -i 4
consolehas "4/4"

testing "Bad idea for EUnit"
! concuerror_console --timeout -1 -f eunit/eunit_sample.erl
consolehas "bad idea"

testing "Simple EUnit use"
cd eunit
erlc eunit_sample.erl
> $Console erl -pa "$(dirname $CONCUERROR)/ebin" -noinput -s eunit_sample test -s erlang halt
consolehas "All 6 tests passed."
rm eunit_sample.beam
cd ..

. footer
