#!/bin/bash

. header

print_blue "$0"

testing "Can find default in path"
rm -rf path
rm -rf foo.beam
mkdir path
erlc -o path src/foo.erl
concuerror_console --pz path -m foo
rm -rf path
good

testing "Script is symlinkable"
rm -rf concuerror
ln -s $(which $CONCUERROR) concuerror
./concuerror 2> $Console
rm -rf concuerror
good

testing "Limited automatic compilation with -m"
cd src
concuerror_console -m foo
good
cd ..

testing "Long short option fixes works"
rm -rf path
rm -rf foo.beam
mkdir path
erlc -o path src/foo.erl
concuerror_console -pz path --ignore-error deadlock --m foo
consolehas "converted to"
rm -rf path

testing "Interleaving bound caps total"
concuerror_console -f src/six.erl -i 4
consolehas "4/4"

testing "Bad idea for EUnit"
! concuerror_console -f src/eunit_sample.erl
consolehas "bad idea"

testing "Simple EUnit use"
cd src
erlc eunit_sample.erl
> $Console erl -pa "$(dirname $CONCUERROR)/../ebin" -noinput \
  -s eunit_sample concuerror_tests \
  -s erlang halt
consolehas "All 3 tests passed."
rm eunit_sample.beam
cd ..

testing "Report unknown arguments in shell invocation"
cd src
erlc from_shell.erl
2> $Console erl -pa "$(dirname $CONCUERROR)/../ebin" -noinput -s from_shell with_unknown -s erlang halt
consolehas "invalid argument: 'unknown_option'"
rm from_shell.beam
cd ..

testing "Report bad entry_point"
cd src
erlc from_shell.erl
2> $Console erl -pa "$(dirname $CONCUERROR)/../ebin" -noinput -s from_shell with_bad_entry -s erlang halt
consolehas "The specified 'entry_point' 'ugly' is invalid."
rm from_shell.beam
cd ..

testing "Report multiple entry_point s"
cd src
erlc from_shell.erl
2> $Console erl -pa "$(dirname $CONCUERROR)/../ebin" -noinput -s from_shell with_multiple_entries -s erlang halt
consolehas "Multiple instances of 'entry_point' specified."
rm from_shell.beam
cd ..

testing "Can recover a -D option without debug_info"
rm -f debug_works.beam
erlc -DN=1 src/debug_works.erl
concuerror_console -m debug_works
consolehas "1/1 interleavings explored"
rm -f debug_works.beam

testing "Decent stacktrace reports"
! concuerror_console -f src/stacktrace.erl
outputhas "[{file,\"src/stacktrace.erl\"},{line,93}]"

testing "Log messages are shown for option errors"
! concuerror_console -module foo
consolehas "Parsing '-module' as '--module odule' (add a dash if this is not desired)"

testing "Warn when erlang:load_nif/2 is detected"
concuerror_console -f src/load_nif.erl
consolehas "Module load_nif contains a call to erlang:load_nif/2."

. footer
