#!/usr/bin/env escript
%% -*- erlang-indent-level: 2 -*-
%%! -noshell

main([ConcuerrorVsn]) ->
  io:format("-define(VSN, ~p).~n",[ConcuerrorVsn]),
  CurrentOTPRelease =
    case erlang:system_info(otp_release) of
      "R" ++ _ -> 16; %% ... or earlier
      [D,U|_] -> list_to_integer([D,U])
    end,
  add_befores_for(CurrentOTPRelease + 1).

add_befores_for(Release) when Release =< 18 ->
  add_before_for(Release),
  add_befores_for(Release + 1);
add_befores_for(_) -> ok.

add_before_for(Release) ->
  io:format("-define(BEFORE_OTP_~p, true).~n", [Release]).
